### PR TITLE
Lightning r333

### PR DESCRIPTION
**Pull request by mikrosk**
This is more like a question than real PR. I had some spare time and since I was doing a lot of USB related tests lately (mainly for #258) I also tested (and recompiled) Lightning drivers (https://www.newtosworld.de/viewtopic.php?t=69&sid=bea0c0bbcc149417266f3369a7d2b674) (btw @czietz is there source code available for https://www.newtosworld.de/viewtopic.php?f=6&t=73 somewhere?).

That got me curious how big _really_ are the differences between those two? The answer is this PR. I've cleaned up it a bit, rebased on master, adjusted the parts changed by @DavidGZ / @Perdrix24 since the R303 release (which seems to be aligned with NETUSB06 release) and ... there's basically nothing left except a few (seemingly useful) fixes.

So what's the deal? Have these two branches finally united since the NETUSB06 / R303 releases?

### CODE REVIEW

**Comment by czietz** [comment]
> @czietz is there source code available for https://www.newtosworld.de/viewtopic.php?f=6&t=73 somewhere

Thank you for reminding me. It's now here https://www.newtosworld.de/viewtopic.php?p=84.

**Comment by czietz** [comment]
I'm afraid that your PR overlapped with the release of our r333 drivers: https://www.newtosworld.de/viewtopic.php?p=86. Sorry!

**Comment by mikrosk** [comment]
Updated to https://www.newtosworld.de/viewtopic.php?t=78&sid=6738421b5c8b6d03b08b957752990bf8#p86. If I'm not mistaken, this release seemed to be based on e9c19315 (NETUSB07 release); rebase to master was clean, no conflicts whatsoever.

So... what prevents us to merge this change @DavidGZ / @Perdrix24 ?

**Comment by DavidGZ** [comment]
> Updated to https://www.newtosworld.de/viewtopic.php?t=78&sid=6738421b5c8b6d03b08b957752990bf8#p86. If I'm not mistaken, this release seemed to be based on [e9c1931](https://github.com/freemint/freemint/commit/e9c19315a2e1bae7a72da3908d06f7b9926d398f) (NETUSB07 release); rebase to master was clean, no conflicts whatsoever.
> 
> So... what prevents us to merge this change @DavidGZ / @Perdrix24 ?

This question should be asked to Christian. What does he prefer to do?

Since the release of the Lighting card I've always thought that it would be nice to keep its driver here, I expressed my opinion to its maintainer, then he was reluctant to do it. If we do the merge but he is not going to use the repository in his coming development of the drivers we will add confusion for him in future bug reports, having two different places to get the binaries from different sources that can be unsynch again.

**Comment by mikrosk** [comment]
>I expressed my opinion to its maintainer, then he was reluctant to do it

My understanding of the situation is as follows: there were basically two reasons. One was personal preference of private development (which is totally OK) but the other one was some supposed changes / design decision in the interest of
performance that might not find the approval of the other FreeMiNT contributors.

Looking at this PR I simply can't find any trace of such changes so this begs the question whether we haven't reached the point when Christian could easily cooperate / push changes to the source tree as he goes? I'm totally fine with him releasing the drivers separately, as part of the "Lightning driver disk" but keeping the source code at one place, that would be the ultimate win for everyone (and the API version problems would disappear with it).

**Comment by Perdrix24** [comment]
@czietz and I had good collaboration since the beginning. We consulted so not to duplicate our work. We even did the Report Protocol for HID together, that went really well, we finished it in a week. We ask each other to test things. I merge his code in netusbee and he merges mine in lightning. He finds bugs in my code and corrects them. 

Keeping separate the code allows us to take different design decisions. However, I think for my part that sharing code can work well. For example, I would like to know more about the SETTER program; it's on my list of things to do to create a GEM program to configure the mouse, for example. Perhaps I can use the SETTER program. The NetUSBee host controller driver could be made faster if we incorporate its assembly portions, or other tricks. When we think about a new major feature, both parties could consult before (at the moment, I often do updates without consulting Christian).

I can also see that the Lightning hardware being commercial, the NetUSBee can be seen as a competitor, and the Thunderstorm team may not want to have development benefit the NetUSBee. However, we are already bringing code between both, just that we more or less do it manually in each, which is more work in the end.

Oops, I just did a GEM USB floppy formatter without telling :-)

**Comment by DavidGZ** [comment]
> 
>     * Perhaps there are design decision where you and I have different opinions. For example, the use of SETTER to configure drivers, or the inline assembly portions in the Lightning driver itself. I guess, this is now for us to figure out together. I would like to request a review of the code. Let me know if you find anything that you require to be changed. Then we can discuss based on concrete findings.
> 
> 

When I added the "switch" for the overcurrent protection mode in the NetUSBee driver, I took a look to SETTER and how you use it in the Lighting driver, at the end I discard it because as far as I know it's a closed source program and being FreeMiNT open source I didn't find it appropriate. But I don't have a strong position on this, many of our setups rely on closed source code (HDDRIVER, NVDI), so for me this is not a stopper for adding Lighting sources in MiNT's repository.

Regarding inline assembler, if the performance gain is noticeable I don't have any problem either.

I made a quick review of the PR, the only thing I found is some minor thing, there is some "duplicate" code within the isp116x driver, there is a function definition to get cookies in global.h that could be used in isp116x-hcd.c

https://github.com/freemint/freemint/blob/648da1cdb947256d32eea01b0c3768e743500113/sys/usb/src.km/global.h#L243-L269

https://github.com/freemint/freemint/blob/648da1cdb947256d32eea01b0c3768e743500113/sys/usb/src.km/ucd/vttusb/isp116x-hcd.c#L154-L182

Also I see that os_header struct is being use in more places now, perhaps we could place its definition in some header file, but this can be done after the merge.

Later I'll do another review with more time, but I don't expect to find anything more.

**Comment by czietz** [comment]
Thank you, Claude and David, for your positive feedback.

SETTER: Yes, you're right, the SETTER GUI program is closed-source. However, an earlier command-line version is included in source code form - albeit without an explicit license - in the [HSModem package](http://atariftp.czietz.de/pub/atari/Modem/hsmoda07.zip). That being said, I'm not an open-source purist, anyway. 😃 A software is fine for me, if it does its job, is available for free (as in "free beer"), and already known to users (since it's used to configure other software such as Big-DOS and HSModem). To me, this seemed a better choice than, e.g., to include an INI file parser into the USB drivers.

Duplicate functions: I suppose when we derived the Lightning drivers (back in 2017) these centralized functions did not exist. That certainly can (and should) be fixed.

Team decision: There were no objections from the Thunderstorm team with regards to merging the Lightning changes back into the official FreeMiNT source tree.

**Comment by DavidGZ** [comment]
> Team decision: There were no objections from the Thunderstorm team with regards to merging the Lightning changes back into the official FreeMiNT source tree.

Great! :-)

**Comment by mikrosk** [comment]
Great news, indeed! If there are no objects from @DavidGZ, I'd grant @czietz write access to our repository (so he doesn't have to create a PR for every single Lightning change he'd like to do). Btw, this offer/question applies also to @Perdrix24, I've seen many commits from you Claude pushed by David so perhaps this would offload his work a bit. But it's up to David, he's our USB guy here. ;-)

As for SETTER, I don't really care either. EtherNAT, Daynaport, Svethlana and perhaps some others were taken as is and included into the source tree without any debates or changes, so it would be really unfair to start to be purists now. It's a separate driver after all, developed by people who develop the hardware as well, so... if they are happy and develop the driver further, users are happy and therefore we are happy. :)

**Comment by DavidGZ** [comment]
> Great news, indeed! If there are no objects from @DavidGZ, I'd grant @czietz write access to our repository (so he doesn't have to create a PR for every single Lightning change he'd like to do). 

@mikrosk I was already thinking of proposing you the same thing, so for me go ahead and give him write rights access.

>Btw, this offer/question applies also to @Perdrix24, I've seen many commits from you Claude pushed by David so perhaps this would offload his work a bit. But it's up to David, he's our USB guy here. ;-)
> 

Regarding @Perdrix24, whatever he decides, I review all the his patches, lately I only change minor cosmetic things so his patches are always ready to be pushed as he sends them to me. But I don't know how comfortable he feels dealing with Github. I don't care to continue reviewing and pushing his patches, the flow is not that much. It's up to him.

**Comment by czietz** [comment]
To simplify the code review, I've made public the changes as individual commits in this repository: https://github.com/czietz/freemint-private/tree/vttusb_local_v4. That might answer questions like "why were these lines added?".

**Comment by Perdrix24** [comment]
> Regarding @Perdrix24, whatever he decides, I review all the his patches, lately I only change minor cosmetic things so his patches are always ready to be pushed as he sends them to me. But I don't know how comfortable he feels dealing with Github. I don't care to continue reviewing and pushing his patches, the flow is not that much. It's up to him.

@DavidGZ I'll exchange with you via email how I handle git and the moment, then perhaps you can suggest  a better way.

**Comment by DavidGZ** [comment]
> To simplify the code review, I've made public the changes as individual commits in this repository: https://github.com/czietz/freemint-private/tree/vttusb_local_v4. That might answer questions like "why were these lines added?".

Thanks! I went though the commits, the only thing I saw that should be edited before merging it's a duplication of a function declaration inside global.h, done in this commit:
https://github.com/czietz/freemint-private/commit/8c3f89501cf5c63ffeffafbd42e614e9b2b6ee8d

https://github.com/czietz/freemint-private/blob/8c3f89501cf5c63ffeffafbd42e614e9b2b6ee8d/sys/usb/src.km/global.h#L171-L173

Out of curiosity, what is the "plm" target for the USB stack used for?

**Comment by czietz** [comment]
> Out of curiosity, what is the "plm" target for the USB stack used for?

"**P**RG with **l**ow **m**emory usage". The standard USB stack consumes quite a lot of RAM, which becomes very noticeable on an ST with only 1 MiB (or even 512 kiB) of RAM. With a slight reduction in functionality (not supporting more than 8 USB devices, not supporting very rare configuration descriptors larger than 16 kiB), the memory footprint is _drastically_ reduced. Put into concrete numbers: Loading regular USB.PRG consumes 252 kiB of RAM, whereas USB_LMEM.PRG (the result of the "plm" target) consumes 112 kiB.

**Comment by mikrosk** [comment]
While we are reviewing the privat tree, @czietz there was another typo I fixed in this PR:https://github.com/czietz/freemint-private/commit/f5e470b009775f433af2e81754464671651deab2#diff-12303546efaece2e6a360288ceb556c4445de4f791d1122ff6021f519bf188afR44

You're missing `ifeq` there which leads to a build failure (another advantage of being in FreeMiNT source tree, you'll get your builds always verified ;) )

**Comment by mikrosk** [comment]
While we are reviewing the privat tree, @czietz there was another typo I fixed in this PR:https://github.com/czietz/freemint-private/commit/f5e470b009775f433af2e81754464671651deab2#diff-12303546efaece2e6a360288ceb556c4445de4f791d1122ff6021f519bf188afR44

You're missing `ifeq` there which leads to a build failure (another advantage of being in FreeMiNT source tree, you'll get your builds always verified ;) )

```
diff --git a/.gitignore b/.gitignore
index 7d9db784..bc3b8982 100644
--- a/.gitignore
+++ b/.gitignore
@@ -55,6 +55,10 @@ sys/usb/src.km/ucd/ehci/pci_bios.c
 sys/usb/src.km/ucd/ehci/pci_xbios.S
 sys/usb/src.km/ucd/ehci/setstack.S
 sys/usb/src.km/ucd/ehci/tosdelay.c
+sys/usb/src.km/ucd/vttusb/crtinit.c
+sys/usb/src.km/ucd/vttusb/delayasm.S
+sys/usb/src.km/ucd/vttusb/entry.S
+sys/usb/src.km/ucd/vttusb/setstack.S
 sys/usb/src.km/udd/eth/crtinit.c
 sys/usb/src.km/udd/eth/entry.S
 sys/usb/src.km/udd/eth/setstack.S
diff --git a/sys/usb/src.km/Makefile.objs b/sys/usb/src.km/Makefile.objs
index c0280d7b..005f3590 100644
--- a/sys/usb/src.km/Makefile.objs
+++ b/sys/usb/src.km/Makefile.objs
@@ -41,7 +41,7 @@ ifeq ($(TARGET),usb.prg)
 # for HDDRIVER modules to work, TOSSSOBJS must be first in OBJS
 OBJS = $(TOSSSOBJS:.S=.o) $(TOSCOBJS:.c=.o) $(SSOBJS:.S=.o) $(COBJS:.c=.o) $(SOBJS:.s=.o)
 STRIPEX = stripex
-else ($(TARGET),usb_lmem.prg)
+else ifeq ($(TARGET),usb_lmem.prg)
 # for HDDRIVER modules to work, TOSSSOBJS must be first in OBJS
 OBJS = $(TOSSSOBJS:.S=.o) $(TOSCOBJS:.c=.o) $(SSOBJS:.S=.o) $(COBJS:.c=.o) $(SOBJS:.s=.o)
 STRIPEX = stripex
diff --git a/sys/usb/src.km/ucd/Makefile b/sys/usb/src.km/ucd/Makefile
index fab5af9c..3e7be986 100644
--- a/sys/usb/src.km/ucd/Makefile
+++ b/sys/usb/src.km/ucd/Makefile
@@ -3,7 +3,7 @@
 #
 
 SHELL = /bin/sh
-SUBDIRS = aranym ehci ethernat netusbee unicorn
+SUBDIRS = aranym ehci ethernat netusbee unicorn vttusb
 
 srcdir = .
 top_srcdir = ../../..
```

**Comment by mikrosk** [comment]
I've added one more commit, to make it part of our Github CI. It's untested, I'll cherry-pick it after Christian's tree will be merged (I'll let him to review & apply my patch above first).

**Comment by czietz** [comment]
The Lightning hardware driver comes in a few variants - each with its own target. I'm afraid I've never found out how to add them to the FreeMiNT build system. My build merely consists of `make`-ing the respective targets from inside the _ucd/vttusb_ folder.

In short, the following targets exist:

- 000: Lightning VME for MegaSTE, MiNT
- 030: Lightning VME for TT, MiNT
- prg: Lightning VME for MegaSTE, TOS
- p30: Lightning VME for TT, TOS
- mst: Lightning ST, MiNT
- pst: Lightning ST, TOS

These are not interchangeable, mainly because the registers are mapped to different addresses.

**Comment by mikrosk** [comment]
No worries @czietz, I've already done it for you. I'm just waiting for you to include the changes from https://github.com/freemint/freemint/pull/260#issuecomment-1173025869, then I'll merge your tree include the Github CI changes on top of it.

I didn't want to complicate things too much, so my proposed output would be:
- USB4TOS: contains prg, p30, pst targets (*.prg) & in addition to usb.prg also usb_lmem.prg
- 000 & ST/E build: contains 000, mst targets (*.ucd)
- 02060, 030 & TT/Falcon build: contains 030 target (blitz030.ucd)

So before running `usb/loader.prg` one has to deactivate the other UCDs but that's OK, it was like this before with other drivers, too.

**Comment by czietz** [comment]
> No worries @czietz, I've already done it for you. I'm just waiting for you to include the changes from [#260 (comment)](https://github.com/freemint/freemint/pull/260#issuecomment-1173025869), then I'll merge your tree and rebase the Github CI changes on top of it.

Just included your patch in my copy at https://github.com/czietz/freemint-private/tree/vttusb_local_v4. Thank you.

> I didn't want to complicate things too much, so my proposed output would be:
> 
>     * USB4TOS: contains prg, p30, pst targets (*.prg) & in addition to usb.prg also usb_lmem.prg
> 
>     * 000 & ST/E build: contains 000, mst targets (*.ucd)
> 
>     * 02060, 030 & TT/Falcon build: contains 030 target (blitz030.ucd)

Sounds good to me.

**Comment by mikrosk** [comment]
... and it's done! Christian's branch has been rebased on top of master, Github CI has already produced first snapshots with the Lightning drivers: https://freemint.github.io/#snapshots and I have created a @freemint/usb team whose members have push access to https://github.com/freemint/freemint.

Thank you for everyone involved!

**Comment by czietz** [comment]
A big thank you to @mikrosk for creating this PR and convincing me that this is the right way!

**Comment by DavidGZ** [comment]
> A big thank you to @mikrosk for creating this PR and convincing me that this is the right way!

I second this!

**Comment by czietz** [comment]
Addendum: The keyboard drivers makes use of a helper program `KEYB_INJ.PRG` to be able to "inject" keypresses into TOS 1.0x; as the proper defined interface for this is only available from TOS 2 onwards. This program has always been included in the Lightning driver disks, but for easier access I just made it available on GitHub, too: https://github.com/czietz/keyboard-injector.

**Comment by Perdrix24** [comment]
Thanks @czietz

**Pull request closed without merging**
