### PR TITLE
Added siocgifindex support and fixed siocgifname

### PR DESCRIPTION
**Pull request by MedourMehdi**
Added siocgifindex support and fixed siocgifname
Check issue #359

### CODE REVIEW

**Comment by th-otto** [comment]
Please think about that again. Did you read my comment in https://github.com/freemint/freemint/issues/363? You simply cannot change kernel interfaces to suddenly expect a completely different type of argument.

**Comment by MedourMehdi** [comment]
siocgifname needs to be refactored in order to call ioctl for ppp & slip devices

**Comment by th-otto** [comment]
You don't need to close this ;) Just do any changes, and either just add them as new commits to your branch, or even force-push them to overwrite your previous changes.

**Comment by MedourMehdi** [comment]
Ah sorry! I didn't know, I'm a newbee!

**Pull request closed without merging**
