### PR TITLE
libkern should only depend on CPU type

### LINKED ISSUE #99: libkern's memset broken on MC68000 (alignment issue)
Odd addresses can be only accessed as single bytes (xxx.B instructions) on the MC68000. memset(), as implemented by libkern, tries to account for that: https://github.com/freemint/freemint/blob/02ceb748073b6159ff4bf9929160bd1ed3ed85e1/sys/libkern/asm/memset.S#L24

However, when libkern is compiled for the 68000, the M68000 macro is not defined:

```
m68k-atari-mint-gcc -I../../.. -m68000 -fgnu89-inline -Werror -mshort -g -O2 -fomit-frame-pointer -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Waggregate-return -c ../memset.S -o memset.o
```

Hence, code is generated that will crash with an address error on a 68000 when the destination address in odd.

### PR DESCRIPTION
**Pull request by mikrosk**
This is supposed to fix #99.

Not sure about applying $(KERNELDEFAULTDEFS) ? Do we them in libkern?

### CODE REVIEW

**Comment by th-otto** [comment]
Why is this needed? It will only pass flags like PCI_BIOS, NO_RAMFS etc. None of these are used in libkern. If they would, we would be in trouble, because then we would need a separate libkern.a for every kernel target.

**Comment by mikrosk** [comment]
Have you actually tried it? This will pass M68xxx defs only. KERNELDEFAULTDEFS will pass the rest and I haven't included it (hence my question above).

**Comment by th-otto** [comment]
>Have you actually tried it?
Since the patch isn't applied yet: no ;)

But looking at KERNELDEFS:
```
ifeq ($(kernel),ara)
MINT = mintara.prg
CPU  = 040
KERNELDEFS = -DARANYM -DM68040 -DWITH_HOSTFS -DBOOTSTRAPABLE -DC_ONLY
MODULEDIRS = xfs/hostfs
endif
``` 

>KERNELDEFAULTDEFS will pass the rest and I haven't included it 

Both would be wrong. That library should only depend on CPU type. The kerneltargets will link to libkern040.a, not libkernara.a. If you compile for multiple targets that use the same cpu type, you will end up linking to a library for which you don't known which flags were used to compile it, depending on which one is compiled first.

Beside that, grepping through the source, i think there are only 2 files that are affected, memset.S as found by christian, and asm/blockcopy.S.

BTW i think the logic in blockcopy.S is wrong (although harmless). When compiling for 040 or better, you could always use the move16 loop, without checking for cpu type.

**Comment by mikrosk** [comment]
Fair enough - actually now I see that other libkern source also check for the __mc__ defs so perhaps it's an oversight. Both issues are addressed in updated commits.

**Comment by th-otto** [comment]
I think the 2nd one is still not quite right ;) I didn't mean to remove the check for actual cpu type altogether. When you use -m68020-60 that should work also on 020 (-m68020-060 will also define __mc68040__, only when you use -m68040 that check can be omitted).

**Comment by mikrosk** [comment]
Hopefully fine now.

**Comment by mikrosk** [comment]
@th-otto ok to merge?

**Comment by th-otto** [comment]
Oh, wait. While looking at it agaiin, i just saw that you inserted an #endif after the first check. Wouldn't that mean that the code now falls into the move16 case when compiled for plain 68000?

**Comment by mikrosk** [comment]
Isn't that guarded by `#if defined(__mc68040__) || defined(__mc68060__)` ?

**Comment by mikrosk** [comment]
Really not sure what you mean:
diff
On 68000, movem + move would be compiled in and then code starting at `blkmv`, isn't that right?

**Comment by th-otto** [comment]
Ah ok, got a wrong look at the first ifdefs, there are now 2. So go ahead ;)

**Pull request merged**
