### PR TITLE
Add SvETHlana driver

### PR DESCRIPTION
**Pull request by jvaltane**
I added svETHana driver from http://nature.tari.org. Build files are based to ethernat driver.

Now I'd like to polish changes witch I made.

### CODE REVIEW

**Comment by mikrosk** [comment]
If you'd like to improve something, feel free to do that in further commits -- the pull request shows all commits from given branch.

Btw, assembler files are named ".S" (capital 's') by convention.

**Comment by vinriviere** [comment]
> Btw, assembler files are named ".S" (capital 's') by convention.
@mikrosk Not by convention, this is mandatory to enable C preprocessing (#ifdef, etc.) hence ColdFire support.

**Comment by mikrosk** [comment]
@jvaltane: I've found the old sources, they are pre-FW10 so we can use it to test regressions.

Could you rebase your PR on top of this: http://ge.tt/8zaxGYj2 ?

**Comment by jvaltane** [comment]
Sure.

Actually I compiled 0.1 driver already, but I'd like to test it work before going any further.

**Comment by jvaltane** [comment]
There is new better pull request.

**Pull request closed without merging**
