### PR TITLE
Merge FreeMiNT docs into one HYP file

### LINKED ISSUE #2: Sort out the doc folder
[There](https://github.com/freemint/freemint/tree/master/doc) are many different things -- txts, hyps, htmls, man pages, ... some of the are copy of each other.

Ideally, we should put html stuff into https://freemint.github.io/freemint, simplify / unify the beginners guide, mint.cnf description etc and have it as simple as possible. 

`gh-pages` branch allows us to have a separate yet related documentation branch for github.io: http://stackoverflow.com/a/21657266/21009

Another option is /docs folder on `master`: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch (that we could keep all together -- both the html result and source in UDO or whatever)

### PR DESCRIPTION
**Pull request by mikrosk**
This is the second part of the process to resolve #2 (the first being https://github.com/freemint/freemint/pull/151), again done by Lars Schmidbauer (a.k.a. Lars or Latz).

I promised to prepare this PR nearly three years ago (!) so I wanted to check out this item from my TODO list before it becomes four. ;-)

Brief summary of changes ("gone" means "moved to freemint.hyp"):

- all text files from $SYSDIR are gone; this cleaned up not only $SYSDIR but also the deployment scripts considerably
- `doc/ChangeLog.old` contains old news, release notes and changelogs
- `doc/atari` moved to `doc/programmer`
- `doc/beginner` gone; the german version moved to `doc/german`
- `doc/cnf.hyp` gone
- `doc/examples` updated (mint.cnf: removed NEWFATFS, removed TZ, paths do not depend on 1-19-XXX, sorted, network section)
- `doc/german`: kept for possible future german documentation (doubtful, but...)
- FAQ, INSTALL (a short `install.txt` is kept in `doc` for random github visitors), block_io.txt, cnf.txt, fatfs.txt, kernels.txt, limits.txt, mintime.txt (its programmer part moved to `doc/programmer`), timezone.txt, mp.txt, mp_list.txt, unixmode.txt: GONE

Apart from that, some additional changes have been done:
- `mint-prg.hyp` is copied to c:\guides so freemint.hyp can reference it
- aranym network configuration tool & script included (and mentioned in mint.cnf)
- added /bin/fscheck.sh and /etc/fstab

Please note that:
- freemint.hyp is not built automatically, @th-otto's `hcp` complains about some stuff so I compiled it with ST-Guide's `hcp.ttp` which didn't complain (maybe you can Thorsten take a look?)
- when copy&pasting `Makefile` from `doc/xaaes` I have noticed that we can output xaaes.html... maybe we could add this to https://freemint.github.io/freemint? (right now it's just output from `doc/programmer/newcall.html`)
- I couldn't fully test it as I Github Actions copy stuff to Thorsten's server but of course not from PRs; hopefully the build process goes as far as stopping just before upload so I'll fix any errors reported afterwards

### CODE REVIEW

**Comment by skaftetryne** [comment]
I have just one comment - these files goes into $sysdir, which in most cases is on an 8+3 filesystem. Directories/filenames like "programmer", "readme.1.15", "ChangeLog.old" etc. are too long. IMO all the files in the release archives should have 8+3 filenames.

**Comment by mikrosk** [comment]
No, this is not a problem: the removed docs are in freemint.hyp and the ones which stayed in `doc` are in the source tree only, as before. So no 8+3 collisions.

**Comment by th-otto** [comment]
Regarding compilation problems of freemint.stg: most of them are harmless. It is mainly the @options line which should be changed to single options, and single @ (like in mail addresses) which should be quoted because the @ has special meaning for inline commands.

What makes be wonder though are the non-ascii characters. They are neither utf-8, nor iso8859, nor atari. To me it  looks like they were convert twice to utf-8 (they are all 3 bytes, but most characters from atari character set can be represented by 2 bytes)

**Comment by th-otto** [comment]
Looks most of them should be copyright signs. Merged & fixed now.

**Comment by mikrosk** [comment]
Many thanks Thorsten. I'm pretty sure there will be a couple of minor issues but that can be fixed as we spot them.

**Pull request merged**
