### PR TITLE
xaaes: fix and refactor shell_find()

### PR DESCRIPTION
**Pull request by mikrosk**
- search for "teradesk.inf" in $HOME ended up looking for /root\teradesk.inf\teradesk.inf

- TeraDesk rejects /root/teradesk.inf and even u:/root/teradesk.inf so the paths have to be GEMDOS-compliant

- wildcard-search wasn't really done neither for client-home nor for current path

==

Initially announced here: https://mikro.naprvyraz.sk/mint/201206/msg00015.html ... it seems that for 12 years nobody has noticed that Teradesk and most likely heaps of others are stubbornly refusing to use $HOME for their settings.

To be fair, unix paths were taken as is also in the Ozk era, it seems that nobody has noticed back then either. Or nobody was using Teradesk. ;)

Anyway, IMHO now the function is much more readable and maintainable.

### CODE REVIEW

**Comment by wongck68** [comment]
settings saved at $HOME will be useful for multi-user systems.When will Mint be for it?I been using Mint for many years and have not logon to it before since i think it is auto login as root?    On Saturday, 17 August 2024 at 06:17:29 am SGT, Miro Kropáček ***@***.***> wrote:  
 
    
   -    
search for "teradesk.inf" in $HOME ended up looking for /root\teradesk.inf\teradesk.inf

   -    
TeraDesk rejects /root/teradesk.inf and even u:/root/teradesk.inf so the paths have to be GEMDOS-compliant

   -    
wildcard-search wasn't really done neither for client-home nor for current path


==

Initially announced here: https://mikro.naprvyraz.sk/mint/201206/msg00015.html ... it seems that for 12 years nobody has noticed that Teradesk and most likely heaps of others are stubbornly refusing to use $HOME for their settings.

To be fair, unix paths were taken as is also in the Ozk era, it seems that nobody has noticed back then either. Or nobody was using Teradesk. ;)

Anyway, IMHO now the function is much more readable and maintainable.

You can view, comment on, or merge this pull request online at:

  https://github.com/freemint/freemint/pull/368

Commit Summary
   
   - 2a95684 xaaes: fix and refactor shell_find()

File Changes 
 
(1 file)
   
   -  M xaaes/src.km/xa_shel.c (278) 

Patch Links:
   
   - https://github.com/freemint/freemint/pull/368.patch
   - https://github.com/freemint/freemint/pull/368.diff

**Comment by mikrosk** [comment]
> When will Mint be for it?I been using Mint for many years and have not logon to it before since i think it is auto login as root?

Not sure what you mean? Swe and others has multiple users on his system for decades. It has always been a core MiNT feature.

**Comment by wongck68** [comment]
Oh, new discovery for me.Can you point me to docs for setting this up?Thanks.    On Sunday, 18 August 2024 at 08:33:27 pm SGT, Miro Kropáček ***@***.***> wrote:  
 
 



When will Mint be for it?I been using Mint for many years and have not logon to it before since i think it is auto login as root?


Not sure what you mean? Swe and others has multiple users on his system for decades. It has always been a core MiNT feature.

**Comment by mikrosk** [comment]
@wongck68 I'd recommend to start with EasyMiNT. It creates a default `root` user for you and you can add as many others as you want.

**Comment by wongck68** [comment]
Ah.... I never used EasyMint, no wonder I am missing it.
    On Sunday, 18 August 2024 at 11:25:06 pm SGT, Miro Kropáček ***@***.***> wrote:  
 
 


@wongck68 I'd recommend to start with EasyMiNT. It creates a default root user for you and you can add as many others as you want.

**Comment by mikrosk** [comment]
I have been using this for the whole weekend, didn't notice anything weird so merging.

**Pull request merged**
