### PR TITLE
please add new widgets

### PR DESCRIPTION
**Pull request by ragnar76**
Hi there,

- i've reworked my xaaes/widgets/gemflat.rsc a bit
- created a new PC GEM widget

that would bee cool :)

bye
Bernd

### CODE REVIEW

**Comment by th-otto** [comment]
Looks like there's something wrong with your PR, it has all commits from ~july 2018 ;)

I guess the actual changes are in [add tos_gem and pc_gem widget](https://github.com/freemint/freemint/pull/162/commits/d06fdcc27c2177a9b8c3055f9bb565536be18acc), or did you change something else?

**Comment by mikrosk** [comment]
Oh, I think you are still using the old master (before rebase which happend a couple of months ago). Can you reset your `master` branch to freemint's master first?

**Comment by ragnar76** [comment]
i could. how?

**Comment by mikrosk** [comment]
@ragnar76 no need to close this PR, as you can see above, your `master` has been updated here as well :) So just put your change on top of your new master, push it and voila, we see your clean change :)

**Comment by ragnar76** [comment]
was a missplaced click. sorry :(

**Comment by ragnar76** [comment]
so... i followed this one here

git remote add upstream /url/to/original/repo
git fetch upstream
git checkout master
git reset --hard upstream/master  
git push origin master --force 

When i now create a pr it looks much smaller now (in fact, only my changes appear) . will open a new one since i have reset my fork

**Comment by mikrosk** [comment]
yup, that was the right procedure.

**Pull request closed without merging**
