### PR TITLE
Rework #344

### PR DESCRIPTION
**Pull request by mikrosk**
As there still isn't an agreement whether the previous implementation of #344 is correct, I have taken a look at it.

Basically I reverted Thorsten's changes, re-fixed it the way @lpgb suggested and tested it again on the clients menu, RSM and toolbar/menu demo. Then I re-added the app_options commit, albeit making `>` the default one as it really nicely shows XaAES approach here. All seems to works all right.

I have also made sure that other changes (removal of dead code, fixing typos etc) from Thorsten's commits are kept.

So let's be technical for a change and:

- @th-otto tell me whether you see some concrete issue with this fix, i.e. whether it breaks something
- @lpgb @gokmase please review (just the two commits, the reverting one is not needed)

Artifact to test: https://github.com/freemint/freemint/actions/runs/10432679403/artifacts/1822995312.

### CODE REVIEW

**Comment by th-otto** [comment]
- you reverted everything, including the changes to the resource and xaaes.rsl
- you still don't get the point of why it did the way i did
- You wanted it to behave like AES/N.AES, but now change the default back to '>'. I don't get that.
- I've already said that i'm working on replacing the client menu, which will conflict with changing that code again.

To make it short: i'm really getting angry. If you think you can do better, then go ahead. But then i'm really thinking about stopping all my efforts here.

**Comment by mikrosk** [comment]
@th-otto so much for the 'keep it technical' part. What you don't realise is that _you_ are making people angry. Those people actually use (even care for) XaAES. For you it's just a matter of taste but if you keep dismissing people's objections, those people will stop using XaAES. Or at least its recent versions.

That's why I'm asking for _technical_ objections from your side. Because if the situation is that:
- you are not happy because I'm reverting your code
- people are happy because they get XaAES to do what they wish

in clear conscience  I simply can't let that code untouched, even if you are 10x better developer than I am.

**Comment by lpgb** [comment]
Here's my take. The original code inserted the indicator into the string exactly like atari's code does with the exception it was off by 1. This could of been fixed with an extremely minimal fix to attach_menu() and detach_menu(). That's what I was expecting. However, an executive decision was made to completely rework it so the indicator was superimposed on top of the menu entry with the "assumption we might need an image in the future". This makes it harder to comply with Atari's rules, plus more overhead, two vdi calls for an assumption that isn't proven. This fundamental change should of been discussed before it was implemented. There would of been pushback from me and possibly others. i'm not mad at anyone, I just wish there was more discussion and communication before big changes are made.

**Comment by wongck68** [comment]
Pretty sad to see you guys tearing it here.
Hanging on to some specs that are 40 years old, how can we progress ?Comparing to NAES and TOS AES.... why?  You should be comparing to something more modern say... Windoze/Linux GUI.Yeah aim for the sky and see how high we can go.Like MyAES has some stuff similar to Windoze GUI (ala mouse over the task bar shows a small window of the application running... blew my mind off or am I just dreaming).
Keep making XaAES work with old programs, that's a priority as we have not many development like work processor, spreadsheet and email clients.May be some users are still using LDW Power or Pheonix instead of Sheets. IDK.
New programs... please go on to the new standard of XaAES.What new standard you ask.... chicken and egg...it will not happen if you guys keep on saying 40 year old standard is the standard.New programs should not just implement stuff... like 3 arrows.... but bring to the group for discussion.
Hey... the 3 arrows means so and so can we do something in AES ?
I know the fun that we all had the last 40 years when we were developing. That was the old cowboy town days where every maverick do whatever he wants as TOS only running 1 application (ok, i am not counting the ACC) and you can have your own nifty GUI doing your own widget and stuff. But now in multitasking where several applications are running, you should try to not show off your 3 arrows or $ or %% or whatever char.As a user, I want it to look similar. 
And of course wants to have newer looking and cleverer GUI.  
May be the whole rework job is needed, not just a band-aid.

my 2 cents....

    On Saturday, 17 August 2024 at 09:55:32 pm SGT, Lon Pursell ***@***.***> wrote:  
 
 


Here's my take. The original code inserted the indicator into the string exactly like atari's code does with the exception it was off by 1. This could of been fixed with an extremely minimal fix to attach_menu() and detach_menu(). That's what I was expecting. However, an executive decision was made to completely rework it so the indicator was superimposed on top of the menu entry with the "assumption we might need an image in the future". This makes it harder to comply with Atari's rules, plus more overhead, two vdi calls for an assumption that isn't proven. This fundamental change should of been discussed before it was implemented. There would of been pushback from me and possibly others. i'm not mad at anyone, I just wish there was more discussion and communication before big changes are made.

**Comment by mikrosk** [comment]
@wongck68 not sure what to take from your comment, it seems like you advocating for both changing XaAES and keeping it as compatible as possible.

I recommend to read up the whole technical discussion if you are interested. It's like not like "hanging on to some specs that are 40 years old", it's more like you have a buffer underflow bug and instead of fixing just the index into array you come up with a new memory allocator. Sure, it may be needed but surely a change like this shouldn't be bundled with such a simple fix.

**Comment by GokMasE** [comment]
>     * @lpgb @GokMasE please review (just the two commits, the reverting one is not needed)

I tested this last night and have no objections - every user case I tried so far has rendered fully as expected. For RSM, XaAES do handle the pre-existing right arrows in the RSC correctly. Essentially both indicators and submenus are positioned accurately.

Unless something new surfaces, the current patch should ensure that any application written to utilize submenus under AES 4.1/N.AES should now look like the respective authors intended also under XaAES.

**Comment by lpgb** [comment]
Are you even familiar with menu_attach() and/or used it in your own software? Do you understand the concept of base level compatibly? Are you ok with the indicator appearing under the submenu which looks broken? I really fail to see your point and you seem to be over generalizing one tiny aspect of one call. If you want something radically different you need to add an entirely new aes call. The "$" should never be seen unless the call is broken, it's a test case well within the guidelines and it gets clobbered. It has a well defined behavior by Atari, see mikro's post in the original issue thread. NAES passed stress test I threw at it, kudos to the author(s) who did their homework. What I find sad is a post like this without first doing any research whatsoever.

Another suggestion. I'd like to see the config option changed so any asc code can be applied. I think asc 175 would look nice and give even more options for personal customization.

Anyway the artifact build passes all my tests, even my stress tests that are fully within Atari's guidelines. The indicator looks consistent across all apps even RSM which attempts use 2 different indicators ends up using only the configured one. 

> Pretty sad to see you guys tearing it here. Hanging on to some specs that are 40 years old, how can we progress ?Comparing to NAES and TOS AES.... why?  You should be comparing to something more modern say... Windoze/Linux GUI.Yeah aim for the sky and see how high we can go.Like MyAES has some stuff similar to Windoze GUI (ala mouse over the task bar shows a small window of the application running... blew my mind off or am I just dreaming). Keep making XaAES work with old programs, that's a priority as we have not many development like work processor, spreadsheet and email clients.May be some users are still using LDW Power or Pheonix instead of Sheets. IDK. New programs... please go on to the new standard of XaAES.What new standard you ask.... chicken and egg...it will not happen if you guys keep on saying 40 year old standard is the standard.New programs should not just implement stuff... like 3 arrows.... but bring to the group for discussion. Hey... the 3 arrows means so and so can we do something in AES ? I know the fun that we all had the last 40 years when we were developing. That was the old cowboy town days where every maverick do whatever he wants as TOS only running 1 application (ok, i am not counting the ACC) and you can have your own nifty GUI doing your own widget and stuff. But now in multitasking where several applications are running, you should try to not show off your 3 arrows or $ or %% or whatever char.As a user, I want it to look similar.  And of course wants to have newer looking and cleverer GUI.   May be the whole rework job is needed, not just a band-aid. my 2 cents.... >

**Comment by lpgb** [comment]
@mikrosk: The artifact build passes all my tests, even my stress tests that are fully within Atari's guidelines. The indicator looks consistent across all apps even RSM which attempts use 2 different indicators ends up using only the configured one. 

Another suggestion. I'd like to see the config option changed if possible so any asc code can be applied. I think asc 175 would look nice and give even more options for personal customization.

>     * @lpgb @GokMasE please review (just the two commits, the reverting one is not needed)

**Comment by wongck68** [comment]
Yes Mikro, correct.Changing XaAES to keep up with the modern times and any great ideas that we see other GUI are having.... and also to be keeping compatible with as many of the old software are possible ( due to lack of new applications).
No Lonny. I do not know those stuff you mentioned especially the technical ones... way above my head.
If that $ char appears, I probably move my mouse over it to see what effect it has.If it pop-down a menu, fine. If it does nothing, fine.So long as the program works as expected, it is great.
May be I have a big tolerance for defective GUI at least for the Atari - I don't mind if arrows or menu rendering is off by an centimeter so long as it register the click. There are many old software that I have come across having GUI issues. may it is my screen resolution, may be it is my number of colours, may be the wrong RSC for that resolution or even may be RSC translation messed something... IDK.

It great that you guys are fixing all these.... even a 1 pixel offset.  Frankly, I will not seen that given my eye sight. 
And so I thank to all of you for contributing to Mint XaAES Emutos GBE.(for giving ordinary users the ability make great stuff)... and keep the platform alive


    On Sunday, 18 August 2024 at 11:20:10 pm SGT, Lon Pursell ***@***.***> wrote:  
 
 


@mikrosk: The artifact build passes all my tests, even my stress tests that are fully within Atari's guidelines. The indicator looks consistent across all apps even RSM which attempts use 2 different indicators ends up using only the configured one.

Another suggestion. I'd like to see the config option changed if possible so any asc code can be applied. I think asc 175 would look nice and give even more options for personal customization.

* @lpgb @GokMasE please review (just the two commits, the reverting one is not needed)

**Comment by wongck68** [comment]
Actually the most important thing for me is that my Falcon is still working, so any software that I am using even if the GUI is not exactly looking what is suppose to be, I will take it. For I do not know when will I cannot use it any more... when will my bird stop flying... I cannot tell.
    On Monday, 19 August 2024 at 12:03:52 am SGT, WongCK ***@***.***> wrote:  
 
  Yes Mikro, correct.Changing XaAES to keep up with the modern times and any great ideas that we see other GUI are having.... and also to be keeping compatible with as many of the old software are possible ( due to lack of new applications).
No Lonny. I do not know those stuff you mentioned especially the technical ones... way above my head.
If that $ char appears, I probably move my mouse over it to see what effect it has.If it pop-down a menu, fine. If it does nothing, fine.So long as the program works as expected, it is great.
May be I have a big tolerance for defective GUI at least for the Atari - I don't mind if arrows or menu rendering is off by an centimeter so long as it register the click. There are many old software that I have come across having GUI issues. may it is my screen resolution, may be it is my number of colours, may be the wrong RSC for that resolution or even may be RSC translation messed something... IDK.

It great that you guys are fixing all these.... even a 1 pixel offset.  Frankly, I will not seen that given my eye sight. 
And so I thank to all of you for contributing to Mint XaAES Emutos GBE.(for giving ordinary users the ability make great stuff)... and keep the platform alive


    On Sunday, 18 August 2024 at 11:20:10 pm SGT, Lon Pursell ***@***.***> wrote:  
 
 


@mikrosk: The artifact build passes all my tests, even my stress tests that are fully within Atari's guidelines. The indicator looks consistent across all apps even RSM which attempts use 2 different indicators ends up using only the configured one.

Another suggestion. I'd like to see the config option changed if possible so any asc code can be applied. I think asc 175 would look nice and give even more options for personal customization.

* @lpgb @GokMasE please review (just the two commits, the reverting one is not needed)

**Comment by lpgb** [comment]
@wongck68: It wasn't off by one pixel, it was in fact off by any entire character width. lol
Please see images: https://github.com/freemint/freemint/issues/344

You could say these features are rarely used, but maybe that has something to do with it not looking correct or working correct. Other recent fixes were also applied. The goal is simply to get the baseline functionality on par with Atari's guidelines and make the feature viable. If we can add a little extra customization along the way that's a win.

> It great that you guys are fixing all these.... even a 1 pixel offset.  Frankly, I will not seen that given my eye sight.  And so I thank to all of you for contributing to Mint XaAES Emutos GBE.(for giving ordinary users the ability make great stuff)... and keep the platform alive

**Comment by mikrosk** [comment]
Confirmed as not regression-free, merging.

Any changes can be built on top of this, ideally as a "request for comments" PR so we avoid further drama.

**Comment by wongck68** [comment]
Thanks for pointing out the comparison picture.Most striking difference, to me, is the arrow compared to the >  sign as indicator. 

I went back to Mint 1.18 and it seems to be using the > sign back then.it's the same for every snapshot that I have including snapshot 731.Only snapshot 0c8, which is the latest I download is using the arrow and the submenu shifted more to the right.This looks more like NAES, which I also tried.Unfortunately my MyAES setup is pretty old and laggy, I cannot even run my app. Not sure what happened, may be I need to get the latest version.
I suddenly remembered that my news feed application uses this submenu function, boy... am I getting old.So I ran it on all the test above, just to see how it looks like.

May be it is just me.... but I felt the > sign is more modern looking.The arrow seems more classical.
As to it covering or not covering that indicator, I have no preferences, so long as the submenu works.May be not covering is better as you can trace where the menu came from... 
    On Monday, 19 August 2024 at 12:36:26 am SGT, Lon Pursell ***@***.***> wrote:  >***@***.***: It wasn't off by one pixel, it was in fact off by any entire character width. lol

**Pull request merged**
