### PR TITLE
add tos_gem and pc_gem widget

### PR DESCRIPTION
**Pull request by ragnar76**
okay, second try

### CODE REVIEW

**Comment by th-otto** [comment]
That patch deletes gemflat.rsc & gemflat.hrd. Was that intended?

**Comment by ragnar76** [comment]
yes, it has the same content but the new filename fits better to the pc gem file

**Comment by th-otto** [comment]
Not completely. The WIDG_LOGO is different (a cross in gemflat, now looks the same as a closer)

**Comment by ragnar76** [comment]
ah, yes. i should start writing changelogs :( i don't know why i have changed it but it looks more consistent now

**Comment by th-otto** [comment]
Ok, merged now. Just renamed the hrd file to lowercase.

**Pull request closed without merging**
